---
name: build

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  core:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    env:
      GOBIN: /home/runner/.local/bin
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Amend Environment Path
      run: |
        mkdir -p /home/runner/.local/bin
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
    - name: Install prerequisites
      run: |
        sudo apt-get --assume-yes update
        sudo apt-get --assume-yes install make
        sudo apt-get --assume-yes install libnss3-tools
        sudo apt-get update
    - name: Setup Environment
      run: |
        mkdir -p .coverage
        echo "*** Current Directory ***"
        pwd
        echo "*** Executable Path ***"
        echo "$PATH" | tr ':' '\n'
        echo "*** Workspace Files ***"
        find .
    - name: Install Go modules
      run: |
        make dep
    - name: Run tests
      run: |
        make test
    - name: Run build
      run: |
        make
    - name: Generate coverage report
      run: make coverage
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: Test Coverage Report
        path: .coverage/coverage.html
